CC		= gcc
AR		= ar

TARGET	= libfcap.a

OBJS 	= init.o core.o interface.o tun.o common.o monitor.o
SRCS 	= $(OBJS:.o=.c)

# Path
INC_PATH	= /usr/include/
LB_PATH 	= /usr/lib/ 

# Flag
CFLAGS 		= -g -Wall
LDFLAGS 	= -levent -lpcap

.SUFFIXES:
.SUFFIXES: .o .c

all:	$(TARGET)

.c.o:
	$(CC) $(CFLAGS) -I$(INC_PATH) -c $<

$(TARGET):	$(OBJS)
	$(AR) ruc $(TARGET) $(OBJS)
	rm -f $(OBJS)

clean:
	rm -f $(OBJS) $(TARGET)
